### ISSUE TITLE
Remember journals I selected last time

### ISSUE THREAD

**Issue by gj330** [Alalalalaki/Econ-Paper-Search#7]
Thanks for designing this website. Super useful!

Maybe it's useful to "remember" the set of journals one selects. If one goes to the website next time, s/he will see the same set of journals s/he selected last time.

That's because people may not be interested in the whole set of journals. During 99% of time, they will drop journals A, B, C. If the website can remember the choice, users have no need to drop these journals every time.

**Comment by Alalalalaki** [comment]
Sorry I don't think there is a way to do this because the website is just a python script running each time accessed. 

Do you think a row of several selection boxes including [top5, top field, macro, labor, ..., all] would help? I think it would allow you to select a bunch of journals by only a few clicks.

**Comment by gj330** [comment]
That's also a good way to go. In addition to top5, maybe also have a "top general interests" including top5 + jeea + ej + aeri + restat? thanks a lot!

**Comment by Alalalalaki** [comment]
I find adding checkbox to control multi-selections is more complicated than I thought. I try another way: I directly add the bundles into the selection choices. So now if you only want to search for  "top general interests", you can first clear all by clicking the small x in the right hand side of the selection box, and then select "general" from the box.

**Comment by gj330** [comment]
thank you!
